notifications:
  email: false
language: java
jdk:
  - oraclejdk8

# command to build
install:
  - "gradle assemble"

# command to run tests
script:
  - "gradle build --stacktrace"
  - "gradle check --stacktrace"

after_success: